src/WebFitDiary/Controllers/AuthController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebFitDiary.Infrastructure;
using WebFitDiary.Models;
using WebFitDiary.ViewModels;

namespace WebFitDiary.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;

        public AuthController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("ProgressControl", "Home");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var signInResult = await _userService.Login(
                    vm.Username,
                    vm.Password);

            if (signInResult.Succeeded)
            {
                return RedirectToAction("ProgressControl", "Home");
            }

            ModelState.AddModelError("", "Username or password is invalid.");
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await _userService.LogOut();
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

src/WebFitDiary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <link rel="stylesheet" href="~/lib/bootswatch/yeti/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
</head>
<body>
    <div id="sidebar">
        <img src="~/images/img1.jpg" id="sidebar-img" alt="sidebar image" />
        <ul class="nav">
            <li><a asp-controller="Home" asp-action="Index">Home</a></li>
            @if (User.Identity.IsAuthenticated)
            {
                <li><a asp-controller="Home" asp-action="ProgressControl">Progress control</a></li>
                <li><a asp-controller="Home" asp-action="TrainingPlan">My training plans</a></li>
                <li><a asp-controller="Auth" asp-action="Logout">Logout</a></li>
            }
            
            @if (!User.Identity.IsAuthenticated)
            {
                <li><a asp-controller="Auth" asp-action="Login">Login</a></li>
                <li><a asp-controller="Account" asp-action="Register">Register</a></li>
            }

        </ul>
    </div>

    <div id="wrapper">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <button id="sidebarToggle" class="btn btn-primary btn-lg">
                            <i class="fa fa-angle-left"></i>
                        </button>
                    </li>
                </ul>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Fit Diary</a>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-print"></i> Print
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="main" class="container-fluid">

            @RenderBody()

        </div>

        <div id="footer" class="container-fluid">
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <h4 class="text-center text-info">&copy; FitDiary Ltd.</h4>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)

    <script src="~/js/site.js"></script>
</body>
</html>